-- ============================================================================
-- 1) CONTEXT
-- ============================================================================
USE DATABASE EM_DB;
USE SCHEMA REVENUE;

-- ============================================================================
-- 2) FILE FORMAT & STAGE (idempotent)
-- ============================================================================

CREATE OR REPLACE FILE FORMAT EM_DB.REVENUE.CSV_FORMAT
  TYPE = 'CSV'
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  DATE_FORMAT = 'YYYY-MM-DD';

CREATE OR REPLACE STAGE EM_DB.REVENUE.CSV_STAGE
  FILE_FORMAT = EM_DB.REVENUE.CSV_FORMAT;

-- ============================================================================
-- 3) (OPTIONAL) CLEAR EXISTING DATA BEFORE RELOAD
--    Comment these out if you want incremental loads instead.
-- ============================================================================

TRUNCATE TABLE IF EXISTS EM_DB.REVENUE.FACT_REVENUE;

TRUNCATE TABLE IF EXISTS EM_DB.REVENUE.DIM_PRODUCT;
TRUNCATE TABLE IF EXISTS EM_DB.REVENUE.DIM_PRODUCT_LINE;
TRUNCATE TABLE IF EXISTS EM_DB.REVENUE.DIM_CUSTOMER;
TRUNCATE TABLE IF EXISTS EM_DB.REVENUE.DIM_TECH_NODE;
TRUNCATE TABLE IF EXISTS EM_DB.REVENUE.DIM_CURRENCY;
TRUNCATE TABLE IF EXISTS EM_DB.REVENUE.DIM_REGION;
TRUNCATE TABLE IF EXISTS EM_DB.REVENUE.DIM_DATE;

-- ============================================================================
-- 4) LOAD DIMENSIONS (in FK-safe order)
-- ============================================================================

-- DIM_DATE
COPY INTO EM_DB.REVENUE.DIM_DATE
FROM @EM_DB.REVENUE.CSV_STAGE/dim_date_2024_2025.csv
FILE_FORMAT = (FORMAT_NAME = EM_DB.REVENUE.CSV_FORMAT)
ON_ERROR = 'CONTINUE';

-- DIM_REGION  (2 columns: REGION_ID, REGION_NAME)
COPY INTO EM_DB.REVENUE.DIM_REGION
FROM @EM_DB.REVENUE.CSV_STAGE/dim_region.csv
FILE_FORMAT = (FORMAT_NAME = EM_DB.REVENUE.CSV_FORMAT)
ON_ERROR = 'CONTINUE';

-- DIM_CURRENCY
COPY INTO EM_DB.REVENUE.DIM_CURRENCY
FROM @EM_DB.REVENUE.CSV_STAGE/dim_currency.csv
FILE_FORMAT = (FORMAT_NAME = EM_DB.REVENUE.CSV_FORMAT)
ON_ERROR = 'CONTINUE';

-- DIM_CUSTOMER
COPY INTO EM_DB.REVENUE.DIM_CUSTOMER
FROM @EM_DB.REVENUE.CSV_STAGE/dim_customer.csv
FILE_FORMAT = (FORMAT_NAME = EM_DB.REVENUE.CSV_FORMAT)
ON_ERROR = 'CONTINUE';

-- DIM_PRODUCT_LINE
COPY INTO EM_DB.REVENUE.DIM_PRODUCT_LINE
FROM @EM_DB.REVENUE.CSV_STAGE/dim_product_line.csv
FILE_FORMAT = (FORMAT_NAME = EM_DB.REVENUE.CSV_FORMAT)
ON_ERROR = 'CONTINUE';

-- DIM_PRODUCT
COPY INTO EM_DB.REVENUE.DIM_PRODUCT
FROM @EM_DB.REVENUE.CSV_STAGE/dim_product.csv
FILE_FORMAT = (FORMAT_NAME = EM_DB.REVENUE.CSV_FORMAT)
ON_ERROR = 'CONTINUE';

-- DIM_TECH_NODE
COPY INTO EM_DB.REVENUE.DIM_TECH_NODE
FROM @EM_DB.REVENUE.CSV_STAGE/dim_tech_node.csv
FILE_FORMAT = (FORMAT_NAME = EM_DB.REVENUE.CSV_FORMAT)
ON_ERROR = 'CONTINUE';

-- ============================================================================
-- 5) LOAD FACT_REVENUE  (uses all the above dimensions)
-- ============================================================================

COPY INTO EM_DB.REVENUE.FACT_REVENUE
FROM @EM_DB.REVENUE.CSV_STAGE/fact_revenue_2024_2025.csv
FILE_FORMAT = (FORMAT_NAME = EM_DB.REVENUE.CSV_FORMAT)
ON_ERROR = 'CONTINUE';

TRUNCATE TABLE IF EXISTS EM_DB.METRICS.FACT_PORTFOLIO_METRIC;
TRUNCATE TABLE IF EXISTS EM_DB.METRICS.FACT_TIMELINE_HEALTH;
TRUNCATE TABLE IF EXISTS EM_DB.OKR.DIM_OKR;

COPY INTO EM_DB.METRICS.FACT_PORTFOLIO_METRIC
(
    METRIC_ID,
    METRIC_NAME,
    METRIC_CATEGORY,
    PERIOD_TYPE,
    PERIOD_LABEL,
    PERIOD_START_DATE,
    PERIOD_END_DATE,
    VALUE_NUM,
    VALUE_UNIT,
    TARGET_NUM,
    TARGET_UNIT,
    PCT_OF_TARGET,
    HEALTH_STATUS
)
FROM @EM_DB.METRICS.CSV_STAGE/fact_portfolio_metric_clean.csv
FILE_FORMAT = (
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    TRIM_SPACE = TRUE
    EMPTY_FIELD_AS_NULL = TRUE
    NULL_IF = ('NULL', 'null', '')
)
ON_ERROR = 'CONTINUE';


COPY INTO EM_DB.METRICS.FACT_TIMELINE_HEALTH
(
    PERIOD_TYPE,
    PERIOD_LABEL,
    PERIOD_START_DATE,
    PERIOD_END_DATE,
    RED_COUNT,
    YELLOW_COUNT,
    GREEN_COUNT,
    TOTAL_COUNT,
    HEALTH_SCORE
)
FROM @EM_DB.METRICS.CSV_STAGE/fact_timeline_health.csv
FILE_FORMAT = (
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    TRIM_SPACE = TRUE
    EMPTY_FIELD_AS_NULL = TRUE
    NULL_IF = ('NULL', 'null', '')
)
ON_ERROR = 'CONTINUE';

COPY INTO EM_DB.OKR.DIM_OKR
(
    OKR_ID,
    OBJECTIVE_TITLE,
    KEY_RESULT_TITLE,
    OWNER,
    STATUS,
    PERIOD_TYPE,
    PERIOD_LABEL,
    PERIOD_START_DATE,
    PERIOD_END_DATE
)
FROM @EM_DB.METRICS.CSV_STAGE/dim_okr.csv
FILE_FORMAT = (
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    TRIM_SPACE = TRUE
    EMPTY_FIELD_AS_NULL = TRUE
    NULL_IF = ('NULL', 'null', '')
)
ON_ERROR = 'CONTINUE';
