/**********************************************************************
-- Enterprise Metrics Data Warehouse Setup - Snowflake
-- Deployment-ready SQL Script
-- Author: Auto-generated
-- Description: Creates warehouse, database, schemas, roles, users,
--              grants, and all core dimensions/fact tables for
--              enterprise metrics platform.
**********************************************************************/

/* ================================
   1?? CREATE WAREHOUSE
================================ */
CREATE OR REPLACE WAREHOUSE EA_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Warehouse for Enterprise Accountability workloads';
  
USE WAREHOUSE EA_WH;  
  
-- Create a database and schema for auth
CREATE OR REPLACE DATABASE AUTH_DB;

CREATE OR REPLACE SCHEMA AUTH_DB.AUTH_SCHEMA;

USE DATABASE AUTH_DB;
USE SCHEMA AUTH_SCHEMA;

CREATE OR REPLACE TABLE AUTH_DB.AUTH_SCHEMA.USERS (
    USER_ID        STRING      NOT NULL DEFAULT UUID_STRING(),
    EMAIL          STRING      NOT NULL,
    PASSWORD_HASH  STRING      NOT NULL,
    CREATED_AT     TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT     TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    LAST_LOGIN_AT  TIMESTAMP_LTZ,

    CONSTRAINT PK_USERS        PRIMARY KEY (USER_ID),
    CONSTRAINT UQ_USERS_EMAIL  UNIQUE (EMAIL)
);

CREATE OR REPLACE TABLE AUTH_DB.AUTH_SCHEMA.USER_SESSIONS (
    SESSION_ID     STRING      NOT NULL DEFAULT UUID_STRING(),
    USER_ID        STRING      NOT NULL,
    REFRESH_TOKEN  STRING      NOT NULL,
    USER_AGENT     STRING,
    IP_ADDRESS     STRING,       -- store as plain string; you can normalize later if needed
    CREATED_AT     TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    EXPIRES_AT     TIMESTAMP_LTZ NOT NULL,

    CONSTRAINT PK_USER_SESSIONS               PRIMARY KEY (SESSION_ID),
    CONSTRAINT FK_USER_SESSIONS_USER
        FOREIGN KEY (USER_ID) REFERENCES AUTH_DB.AUTH_SCHEMA.USERS(USER_ID),
    CONSTRAINT UQ_USER_SESSIONS_REFRESH_TOKEN UNIQUE (REFRESH_TOKEN)
);
  

CREATE OR REPLACE DATABASE EM_DB;

CREATE OR REPLACE SCHEMA EM_DB.METRICS;

CREATE OR REPLACE TABLE EM_DB.METRICS.FACT_PORTFOLIO_METRIC (
    METRIC_ID            STRING,
    METRIC_NAME          STRING,      -- Revenue, Profitability, etc.
    METRIC_CATEGORY      STRING,      -- FINANCIAL | DELIVERY | CUSTOMER | PEOPLE | RISK | GOVERNANCE
    PERIOD_TYPE          STRING,      -- MONTH | QUARTER | YEAR
    PERIOD_LABEL         STRING,      -- 2025-01, 2025-Q1, 2025
    PERIOD_START_DATE    DATE,
    PERIOD_END_DATE      DATE,
    VALUE_NUM            FLOAT,       -- The “65”, “78”, “32”, etc.
    VALUE_UNIT           STRING,      -- %
    TARGET_NUM           FLOAT,       -- Optional
    TARGET_UNIT          STRING,
    PCT_OF_TARGET        FLOAT,
    HEALTH_STATUS        STRING,      -- GOOD | WARN | BAD
    UPDATED_AT           TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE EM_DB.METRICS.FACT_TIMELINE_HEALTH (
    PERIOD_TYPE          STRING,
    PERIOD_LABEL         STRING,
    PERIOD_START_DATE    DATE,
    PERIOD_END_DATE      DATE,
    RED_COUNT            INTEGER,
    YELLOW_COUNT         INTEGER,
    GREEN_COUNT          INTEGER,
    TOTAL_COUNT          INTEGER,
    HEALTH_SCORE         FLOAT,
    UPDATED_AT           TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE SCHEMA EM_DB.OKR;


CREATE OR REPLACE TABLE EM_DB.OKR.DIM_OKR (
    OKR_ID               STRING,
    OBJECTIVE_TITLE      STRING,
    KEY_RESULT_TITLE     STRING,
    OWNER                STRING,
    STATUS               STRING,       -- ON_TRACK | AT_RISK | BEHIND
    PERIOD_TYPE          STRING,
    PERIOD_LABEL         STRING,
    PERIOD_START_DATE    DATE,
    PERIOD_END_DATE      DATE,
    UPDATED_AT           TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE SCHEMA EM_DB.REVENUE;

CREATE OR REPLACE TABLE EM_DB.REVENUE.DIM_DATE (
  DATE_KEY DATE COMMENT 'Calendar date key',
  YEAR NUMBER COMMENT 'Calendar year',
  QUARTER NUMBER COMMENT 'Calendar quarter (1-4)',
  MONTH NUMBER COMMENT 'Calendar month (1-12)',
  WEEK NUMBER COMMENT 'ISO week number',
  CONSTRAINT DIM_DATE_PK PRIMARY KEY (DATE_KEY)
);

CREATE OR REPLACE TABLE EM_DB.REVENUE.DIM_REGION (
  REGION_ID STRING COMMENT 'Region code (NA, TW, KR, CN, JP, EU)',
  REGION_NAME STRING COMMENT 'Region name',
  CONSTRAINT DIM_REGION_PK PRIMARY KEY (REGION_ID)
);

CREATE OR REPLACE TABLE EM_DB.REVENUE.DIM_CURRENCY (
  CURRENCY_CODE STRING COMMENT 'Currency code (USD, TWD, etc.)',
  CURRENCY_NAME STRING COMMENT 'Currency name',
  CONSTRAINT DIM_CURRENCY_PK PRIMARY KEY (CURRENCY_CODE)
);

CREATE OR REPLACE TABLE EM_DB.REVENUE.DIM_CUSTOMER (
  CUSTOMER_ID STRING COMMENT 'Customer identifier',
  CUSTOMER_NAME STRING COMMENT 'Customer name',
  REGION_ID STRING COMMENT 'Home region',
  CONSTRAINT DIM_CUSTOMER_PK PRIMARY KEY (CUSTOMER_ID),
  CONSTRAINT FK_DIM_CUSTOMER_REGION_ID FOREIGN KEY (REGION_ID) REFERENCES EM_DB.REVENUE.DIM_REGION (REGION_ID)
);

CREATE OR REPLACE TABLE EM_DB.REVENUE.DIM_PRODUCT_LINE (
  PRODUCT_LINE_ID STRING COMMENT 'Product line identifier',
  PRODUCT_LINE_NAME STRING COMMENT 'Product line name',
  CONSTRAINT DIM_PRODUCT_LINE_PK PRIMARY KEY (PRODUCT_LINE_ID)
);

CREATE OR REPLACE TABLE EM_DB.REVENUE.DIM_PRODUCT (
  PRODUCT_ID STRING COMMENT 'Tool/Platform identifier',
  PRODUCT_NAME STRING COMMENT 'Commercial tool name',
  PRODUCT_LINE_ID STRING COMMENT 'Owning product line',
  CONSTRAINT DIM_PRODUCT_PK PRIMARY KEY (PRODUCT_ID),
  CONSTRAINT FK_DIM_PRODUCT_PRODUCT_LINE_ID FOREIGN KEY (PRODUCT_LINE_ID) REFERENCES EM_DB.REVENUE.DIM_PRODUCT_LINE (PRODUCT_LINE_ID)
);

CREATE OR REPLACE TABLE EM_DB.REVENUE.DIM_TECH_NODE (
  TECH_NODE_ID STRING COMMENT 'Technology node ID',
  TECH_NODE_NAME STRING COMMENT 'e.g., 3nm, 5nm, 7nm',
  CONSTRAINT DIM_TECH_NODE_PK PRIMARY KEY (TECH_NODE_ID)
);

CREATE OR REPLACE TABLE EM_DB.REVENUE.FACT_REVENUE (
  ORDER_ID STRING COMMENT 'Order line identifier',
  REVENUE_TYPE STRING COMMENT 'CAPEX_TOOL | UPGRADE | SPARES | SERVICE',
  CUSTOMER_ID STRING COMMENT 'Customer',
  REGION_ID STRING COMMENT 'Region',
  PRODUCT_LINE_ID STRING COMMENT 'Product line',
  PRODUCT_ID STRING COMMENT 'Tool',
  TECH_NODE_ID STRING COMMENT 'Tech node',
  CURRENCY_CODE STRING COMMENT 'Transaction currency',
  BOOKING_DATE DATE COMMENT 'Order booking date',
  PLANNED_SHIP_DATE DATE COMMENT 'Planned shipment',
  SHIP_DATE DATE COMMENT 'Actual shipment',
  ACCEPTANCE_DATE DATE COMMENT 'Factory acceptance (if required)',
  FOB_TERMS STRING COMMENT 'FOB_SHIP_POINT | FOB_DESTINATION',
  REVREC_DATE DATE COMMENT 'Revenue recognition date',
  GROSS_PRICE_USD NUMBER(18,2) COMMENT 'List price in USD',
  DISCOUNT_RATE NUMBER(6,4) COMMENT 'Discount rate applied',
  NET_REVENUE_USD NUMBER(18,2) COMMENT 'Net revenue per line in USD',
  NET_REVENUE_LOCAL NUMBER(18,2) COMMENT 'Net revenue in local currency',
  QTY NUMBER COMMENT 'Quantity',
  YEAR NUMBER COMMENT 'Derived: REVREC year',
  QUARTER NUMBER COMMENT 'Derived: REVREC quarter',
  MONTH NUMBER COMMENT 'Derived: REVREC month',
  REVENUE_USD_TOTAL NUMBER(18,2) COMMENT 'NET_REVENUE_USD * QTY',
  CONSTRAINT FACT_REVENUE_PK PRIMARY KEY (ORDER_ID),
  CONSTRAINT FK_FACT_REVENUE_CUSTOMER_ID FOREIGN KEY (CUSTOMER_ID) REFERENCES EM_DB.REVENUE.DIM_CUSTOMER (CUSTOMER_ID),
  CONSTRAINT FK_FACT_REVENUE_REGION_ID FOREIGN KEY (REGION_ID) REFERENCES EM_DB.REVENUE.DIM_REGION (REGION_ID),
  CONSTRAINT FK_FACT_REVENUE_PRODUCT_LINE_ID FOREIGN KEY (PRODUCT_LINE_ID) REFERENCES EM_DB.REVENUE.DIM_PRODUCT_LINE (PRODUCT_LINE_ID),
  CONSTRAINT FK_FACT_REVENUE_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES EM_DB.REVENUE.DIM_PRODUCT (PRODUCT_ID),
  CONSTRAINT FK_FACT_REVENUE_TECH_NODE_ID FOREIGN KEY (TECH_NODE_ID) REFERENCES EM_DB.REVENUE.DIM_TECH_NODE (TECH_NODE_ID),
  CONSTRAINT FK_FACT_REVENUE_CURRENCY_CODE FOREIGN KEY (CURRENCY_CODE) REFERENCES EM_DB.REVENUE.DIM_CURRENCY (CURRENCY_CODE)
);

CREATE OR REPLACE SCHEMA EM_DB.GOVERNANCE;

CREATE OR REPLACE TABLE EM_DB.GOVERNANCE.ACTION_ITEMS (
  ACTION_ID            STRING        DEFAULT UUID_STRING() COMMENT 'Primary key',
  TITLE                STRING        NOT NULL COMMENT 'Short action title',
  DESCRIPTION          STRING        COMMENT 'Optional details',
  STATUS               STRING        DEFAULT 'OPEN' COMMENT 'OPEN | IN_PROGRESS | BLOCKED | DONE | CANCELED',
  PRIORITY             STRING        DEFAULT 'MEDIUM' COMMENT 'LOW | MEDIUM | HIGH | CRITICAL',

  ASSIGNEE_NAME        STRING        NOT NULL COMMENT 'Person assigned (display name)',
  ASSIGNEE_EMAIL       STRING        COMMENT 'Optional email',
  ASSIGNER_NAME        STRING        COMMENT 'Who assigned it',
  ASSIGNER_EMAIL       STRING        COMMENT 'Optional email',

  DUE_DATE             DATE          NOT NULL COMMENT 'Due date (user selected)',
  UPDATED_BY_NAME      STRING        COMMENT 'Last updater (optional)',
  UPDATED_BY_EMAIL     STRING        COMMENT 'Last updater email (optional)',

  CONTEXT_SCREEN       STRING        COMMENT 'e.g., company-vision | revenue | risks',
  CONTEXT_METRIC_NAME  STRING        COMMENT 'e.g., Revenue, NPS, OTD%',
  CONTEXT_ENTITY_ID    STRING        COMMENT 'Optional: id of project/risk/order/etc',
  CONTEXT_URL          STRING        COMMENT 'Optional deep-link to UI route',

  CREATED_AT           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  COMPLETED_AT         TIMESTAMP_NTZ COMMENT 'When status became DONE',
  IS_DELETED           BOOLEAN       DEFAULT FALSE
);

-- Helpful clustering for common queries (assignee, due date)
ALTER TABLE EM_DB.GOVERNANCE.ACTION_ITEMS CLUSTER BY (ASSIGNEE_EMAIL, DUE_DATE);

-- Optional: View for "active" items
CREATE OR REPLACE VIEW EM_DB.GOVERNANCE.V_ACTION_ITEMS_ACTIVE AS
SELECT *
FROM EM_DB.GOVERNANCE.ACTION_ITEMS
WHERE IS_DELETED = FALSE AND STATUS <> 'DONE';


CREATE OR REPLACE FILE FORMAT EM_DB.REVENUE.CSV_FORMAT
  TYPE = 'CSV'
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  DATE_FORMAT = 'YYYY-MM-DD';

CREATE OR REPLACE STAGE EM_DB.REVENUE.CSV_STAGE
  FILE_FORMAT = EM_DB.REVENUE.CSV_FORMAT;
  
-- Command line 
-- C:\Users\<your-username>\.snowsql\config

-- snowsql -c em -q "PUT file://dim_date_2024_2025.csv @EM_DB.REVENUE.CSV_STAGE AUTO_COMPRESS=FALSE"
-- snowsql -c em -q "PUT file://dim_region.csv         @EM_DB.REVENUE.CSV_STAGE AUTO_COMPRESS=FALSE"
-- snowsql -c em -q "PUT file://dim_currency.csv       @EM_DB.REVENUE.CSV_STAGE AUTO_COMPRESS=FALSE"
-- snowsql -c em -q "PUT file://dim_customer.csv       @EM_DB.REVENUE.CSV_STAGE AUTO_COMPRESS=FALSE"
-- snowsql -c em -q "PUT file://dim_product_line.csv   @EM_DB.REVENUE.CSV_STAGE AUTO_COMPRESS=FALSE"
-- snowsql -c em -q "PUT file://dim_product.csv        @EM_DB.REVENUE.CSV_STAGE AUTO_COMPRESS=FALSE"
-- snowsql -c em -q "PUT file://dim_tech_node.csv      @EM_DB.REVENUE.CSV_STAGE AUTO_COMPRESS=FALSE"
-- snowsql -c em -q "PUT file://fact_revenue_2024_2025.csv @EM_DB.REVENUE.CSV_STAGE AUTO_COMPRESS=FALSE"  

-- DIM_DATE
COPY INTO EM_DB.REVENUE.DIM_DATE
FROM @EM_DB.REVENUE.CSV_STAGE/dim_date_2024_2025.csv
FILE_FORMAT = (FORMAT_NAME = EM_DB.REVENUE.CSV_FORMAT)
ON_ERROR = 'CONTINUE';

-- DIM_REGION  (2 columns: REGION_ID, REGION_NAME)
COPY INTO EM_DB.REVENUE.DIM_REGION
FROM @EM_DB.REVENUE.CSV_STAGE/dim_region.csv
FILE_FORMAT = (FORMAT_NAME = EM_DB.REVENUE.CSV_FORMAT)
ON_ERROR = 'CONTINUE';

-- DIM_CURRENCY
COPY INTO EM_DB.REVENUE.DIM_CURRENCY
FROM @EM_DB.REVENUE.CSV_STAGE/dim_currency.csv
FILE_FORMAT = (FORMAT_NAME = EM_DB.REVENUE.CSV_FORMAT)
ON_ERROR = 'CONTINUE';

-- DIM_CUSTOMER
COPY INTO EM_DB.REVENUE.DIM_CUSTOMER
FROM @EM_DB.REVENUE.CSV_STAGE/dim_customer.csv
FILE_FORMAT = (FORMAT_NAME = EM_DB.REVENUE.CSV_FORMAT)
ON_ERROR = 'CONTINUE';

-- DIM_PRODUCT_LINE
COPY INTO EM_DB.REVENUE.DIM_PRODUCT_LINE
FROM @EM_DB.REVENUE.CSV_STAGE/dim_product_line.csv
FILE_FORMAT = (FORMAT_NAME = EM_DB.REVENUE.CSV_FORMAT)
ON_ERROR = 'CONTINUE';

-- DIM_PRODUCT
COPY INTO EM_DB.REVENUE.DIM_PRODUCT
FROM @EM_DB.REVENUE.CSV_STAGE/dim_product.csv
FILE_FORMAT = (FORMAT_NAME = EM_DB.REVENUE.CSV_FORMAT)
ON_ERROR = 'CONTINUE';

-- DIM_TECH_NODE
COPY INTO EM_DB.REVENUE.DIM_TECH_NODE
FROM @EM_DB.REVENUE.CSV_STAGE/dim_tech_node.csv
FILE_FORMAT = (FORMAT_NAME = EM_DB.REVENUE.CSV_FORMAT)
ON_ERROR = 'CONTINUE';

CREATE OR REPLACE STAGE EM_DB.METRICS.CSV_STAGE;