/**********************************************************************
-- Enterprise Metrics Data Warehouse Setup - Snowflake
-- Deployment-ready SQL Script
-- Author: Auto-generated
-- Description: Creates warehouse, database, schemas, roles, users,
--              grants, and all core dimensions/fact tables for
--              enterprise metrics platform.
**********************************************************************/

/* ================================
   1?? CREATE WAREHOUSE
================================ */
CREATE OR REPLACE WAREHOUSE EA_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Warehouse for Enterprise Accountability workloads';
  
USE WAREHOUSE EA_WH;  
  
-- Create a database and schema for auth
CREATE OR REPLACE DATABASE AUTH_DB;

CREATE OR REPLACE SCHEMA AUTH_DB.AUTH_SCHEMA;

USE DATABASE AUTH_DB;
USE SCHEMA AUTH_SCHEMA;

CREATE OR REPLACE TABLE AUTH_DB.AUTH_SCHEMA.USERS (
    USER_ID        STRING      NOT NULL DEFAULT UUID_STRING(),
    EMAIL          STRING      NOT NULL,
    PASSWORD_HASH  STRING      NOT NULL,
    CREATED_AT     TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT     TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    LAST_LOGIN_AT  TIMESTAMP_LTZ,

    CONSTRAINT PK_USERS        PRIMARY KEY (USER_ID),
    CONSTRAINT UQ_USERS_EMAIL  UNIQUE (EMAIL)
);

CREATE OR REPLACE TABLE AUTH_DB.AUTH_SCHEMA.USER_SESSIONS (
    SESSION_ID     STRING      NOT NULL DEFAULT UUID_STRING(),
    USER_ID        STRING      NOT NULL,
    REFRESH_TOKEN  STRING      NOT NULL,
    USER_AGENT     STRING,
    IP_ADDRESS     STRING,       -- store as plain string; you can normalize later if needed
    CREATED_AT     TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    EXPIRES_AT     TIMESTAMP_LTZ NOT NULL,

    CONSTRAINT PK_USER_SESSIONS               PRIMARY KEY (SESSION_ID),
    CONSTRAINT FK_USER_SESSIONS_USER
        FOREIGN KEY (USER_ID) REFERENCES AUTH_DB.AUTH_SCHEMA.USERS(USER_ID),
    CONSTRAINT UQ_USER_SESSIONS_REFRESH_TOKEN UNIQUE (REFRESH_TOKEN)
);
  

CREATE OR REPLACE DATABASE EM_DB;
CREATE OR REPLACE SCHEMA EM_DB.CUSTOMER;
CREATE OR REPLACE SCHEMA EM_DB.GOV;
CREATE OR REPLACE SCHEMA EM_DB.HC;
CREATE OR REPLACE SCHEMA EM_DB.PMO;
CREATE OR REPLACE SCHEMA EM_DB.PROFITABILITY;
CREATE OR REPLACE SCHEMA EM_DB.REVENUE;
CREATE OR REPLACE SCHEMA EM_DB.RISK;

CREATE OR REPLACE TABLE EM_DB.REVENUE.DIM_DATE (
  DATE_KEY DATE COMMENT 'Calendar date key',
  YEAR NUMBER COMMENT 'Calendar year',
  QUARTER NUMBER COMMENT 'Calendar quarter (1-4)',
  MONTH NUMBER COMMENT 'Calendar month (1-12)',
  WEEK NUMBER COMMENT 'ISO week number',
  CONSTRAINT DIM_DATE_PK PRIMARY KEY (DATE_KEY)
);

CREATE OR REPLACE TABLE EM_DB.REVENUE.DIM_REGION (
  REGION_ID STRING COMMENT 'Region code (NA, TW, KR, CN, JP, EU)',
  REGION_NAME STRING COMMENT 'Region name',
  CONSTRAINT DIM_REGION_PK PRIMARY KEY (REGION_ID)
);

CREATE OR REPLACE TABLE EM_DB.REVENUE.DIM_CURRENCY (
  CURRENCY_CODE STRING COMMENT 'Currency code (USD, TWD, etc.)',
  CURRENCY_NAME STRING COMMENT 'Currency name',
  CONSTRAINT DIM_CURRENCY_PK PRIMARY KEY (CURRENCY_CODE)
);

CREATE OR REPLACE TABLE EM_DB.REVENUE.DIM_CUSTOMER (
  CUSTOMER_ID STRING COMMENT 'Customer identifier',
  CUSTOMER_NAME STRING COMMENT 'Customer name',
  REGION_ID STRING COMMENT 'Home region',
  CONSTRAINT DIM_CUSTOMER_PK PRIMARY KEY (CUSTOMER_ID),
  CONSTRAINT FK_DIM_CUSTOMER_REGION_ID FOREIGN KEY (REGION_ID) REFERENCES EM_DB.REVENUE.DIM_REGION (REGION_ID)
);

CREATE OR REPLACE TABLE EM_DB.REVENUE.DIM_PRODUCT_LINE (
  PRODUCT_LINE_ID STRING COMMENT 'Product line identifier',
  PRODUCT_LINE_NAME STRING COMMENT 'Product line name',
  CONSTRAINT DIM_PRODUCT_LINE_PK PRIMARY KEY (PRODUCT_LINE_ID)
);

CREATE OR REPLACE TABLE EM_DB.REVENUE.DIM_PRODUCT (
  PRODUCT_ID STRING COMMENT 'Tool/Platform identifier',
  PRODUCT_NAME STRING COMMENT 'Commercial tool name',
  PRODUCT_LINE_ID STRING COMMENT 'Owning product line',
  CONSTRAINT DIM_PRODUCT_PK PRIMARY KEY (PRODUCT_ID),
  CONSTRAINT FK_DIM_PRODUCT_PRODUCT_LINE_ID FOREIGN KEY (PRODUCT_LINE_ID) REFERENCES EM_DB.REVENUE.DIM_PRODUCT_LINE (PRODUCT_LINE_ID)
);

CREATE OR REPLACE TABLE EM_DB.REVENUE.DIM_TECH_NODE (
  TECH_NODE_ID STRING COMMENT 'Technology node ID',
  TECH_NODE_NAME STRING COMMENT 'e.g., 3nm, 5nm, 7nm',
  CONSTRAINT DIM_TECH_NODE_PK PRIMARY KEY (TECH_NODE_ID)
);

CREATE OR REPLACE TABLE EM_DB.REVENUE.FACT_REVENUE (
  ORDER_ID STRING COMMENT 'Order line identifier',
  REVENUE_TYPE STRING COMMENT 'CAPEX_TOOL | UPGRADE | SPARES | SERVICE',
  CUSTOMER_ID STRING COMMENT 'Customer',
  REGION_ID STRING COMMENT 'Region',
  PRODUCT_LINE_ID STRING COMMENT 'Product line',
  PRODUCT_ID STRING COMMENT 'Tool',
  TECH_NODE_ID STRING COMMENT 'Tech node',
  CURRENCY_CODE STRING COMMENT 'Transaction currency',
  BOOKING_DATE DATE COMMENT 'Order booking date',
  PLANNED_SHIP_DATE DATE COMMENT 'Planned shipment',
  SHIP_DATE DATE COMMENT 'Actual shipment',
  ACCEPTANCE_DATE DATE COMMENT 'Factory acceptance (if required)',
  FOB_TERMS STRING COMMENT 'FOB_SHIP_POINT | FOB_DESTINATION',
  REVREC_DATE DATE COMMENT 'Revenue recognition date',
  GROSS_PRICE_USD NUMBER(18,2) COMMENT 'List price in USD',
  DISCOUNT_RATE NUMBER(6,4) COMMENT 'Discount rate applied',
  NET_REVENUE_USD NUMBER(18,2) COMMENT 'Net revenue per line in USD',
  NET_REVENUE_LOCAL NUMBER(18,2) COMMENT 'Net revenue in local currency',
  QTY NUMBER COMMENT 'Quantity',
  YEAR NUMBER COMMENT 'Derived: REVREC year',
  QUARTER NUMBER COMMENT 'Derived: REVREC quarter',
  MONTH NUMBER COMMENT 'Derived: REVREC month',
  REVENUE_USD_TOTAL NUMBER(18,2) COMMENT 'NET_REVENUE_USD * QTY',
  CONSTRAINT FACT_REVENUE_PK PRIMARY KEY (ORDER_ID),
  CONSTRAINT FK_FACT_REVENUE_CUSTOMER_ID FOREIGN KEY (CUSTOMER_ID) REFERENCES EM_DB.REVENUE.DIM_CUSTOMER (CUSTOMER_ID),
  CONSTRAINT FK_FACT_REVENUE_REGION_ID FOREIGN KEY (REGION_ID) REFERENCES EM_DB.REVENUE.DIM_REGION (REGION_ID),
  CONSTRAINT FK_FACT_REVENUE_PRODUCT_LINE_ID FOREIGN KEY (PRODUCT_LINE_ID) REFERENCES EM_DB.REVENUE.DIM_PRODUCT_LINE (PRODUCT_LINE_ID),
  CONSTRAINT FK_FACT_REVENUE_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES EM_DB.REVENUE.DIM_PRODUCT (PRODUCT_ID),
  CONSTRAINT FK_FACT_REVENUE_TECH_NODE_ID FOREIGN KEY (TECH_NODE_ID) REFERENCES EM_DB.REVENUE.DIM_TECH_NODE (TECH_NODE_ID),
  CONSTRAINT FK_FACT_REVENUE_CURRENCY_CODE FOREIGN KEY (CURRENCY_CODE) REFERENCES EM_DB.REVENUE.DIM_CURRENCY (CURRENCY_CODE)
);

CREATE OR REPLACE TABLE EM_DB.PROFITABILITY.DIM_COST_DRIVER (
  COST_DRIVER_ID STRING COMMENT 'Cost driver key',
  PRODUCT_LINE_ID STRING COMMENT 'Links to product line',
  AVG_COGS_PCT NUMBER(5,2) COMMENT 'Average direct cost % of revenue',
  AVG_OPEX_PCT NUMBER(5,2) COMMENT 'Allocated opex % of revenue',
  CONSTRAINT DIM_COST_DRIVER_PK PRIMARY KEY (COST_DRIVER_ID),
  CONSTRAINT FK_DIM_COST_DRIVER_PRODUCT_LINE_ID FOREIGN KEY (PRODUCT_LINE_ID) REFERENCES EM_DB.REVENUE.DIM_PRODUCT_LINE (PRODUCT_LINE_ID)
);

CREATE OR REPLACE TABLE EM_DB.PROFITABILITY.FACT_PROFITABILITY (
  ORDER_ID STRING COMMENT 'Back-reference to revenue line',
  PRODUCT_LINE_ID STRING COMMENT 'Product line',
  REVENUE_TYPE STRING COMMENT 'Revenue category',
  CUSTOMER_ID STRING COMMENT 'Customer',
  REVREC_DATE DATE COMMENT 'Recognition date',
  NET_REVENUE_USD NUMBER(18,2) COMMENT 'Recognized revenue',
  COGS_USD NUMBER(18,2) COMMENT 'Direct costs',
  GROSS_PROFIT_USD NUMBER(18,2) COMMENT 'NET_REVENUE - COGS',
  GROSS_MARGIN_PCT NUMBER(6,2) COMMENT 'Gross margin %',
  OPEX_ALLOC_USD NUMBER(18,2) COMMENT 'Allocated opex',
  OPERATING_PROFIT_USD NUMBER(18,2) COMMENT 'Operating profit',
  CONSTRAINT FACT_PROFITABILITY_PK PRIMARY KEY (ORDER_ID),
  CONSTRAINT FK_FACT_PROFITABILITY_ORDER_ID FOREIGN KEY (ORDER_ID) REFERENCES EM_DB.REVENUE.FACT_REVENUE (ORDER_ID),
  CONSTRAINT FK_FACT_PROFITABILITY_PRODUCT_LINE_ID FOREIGN KEY (PRODUCT_LINE_ID) REFERENCES EM_DB.REVENUE.DIM_PRODUCT_LINE (PRODUCT_LINE_ID),
  CONSTRAINT FK_FACT_PROFITABILITY_CUSTOMER_ID FOREIGN KEY (CUSTOMER_ID) REFERENCES EM_DB.REVENUE.DIM_CUSTOMER (CUSTOMER_ID)
);

CREATE OR REPLACE TABLE EM_DB.PMO.DIM_PROGRAM (
  PROGRAM_ID STRING COMMENT 'Program identifier',
  PROGRAM_NAME STRING COMMENT 'Program name',
  CONSTRAINT DIM_PROGRAM_PK PRIMARY KEY (PROGRAM_ID)
);

CREATE OR REPLACE TABLE EM_DB.PMO.DIM_STAGE_GATE (
  STAGE_ID NUMBER(2) COMMENT 'Stage-gate identifier',
  STAGE_NAME STRING COMMENT 'Stage name',
  STAGE_ORDER NUMBER(2) COMMENT 'Ordering for gates',
  CONSTRAINT DIM_STAGE_GATE_PK PRIMARY KEY (STAGE_ID)
);

CREATE OR REPLACE TABLE EM_DB.PMO.DIM_TEAM (
  TEAM_ID STRING COMMENT 'Team identifier',
  TEAM_NAME STRING COMMENT 'Team name',
  CONSTRAINT DIM_TEAM_PK PRIMARY KEY (TEAM_ID)
);

CREATE OR REPLACE TABLE EM_DB.PMO.DIM_PROJECT (
  PROJECT_ID STRING COMMENT 'Project identifier',
  PROJECT_NAME STRING COMMENT 'Project name',
  PROGRAM_ID STRING COMMENT 'Owning program',
  PRODUCT_LINE_ID STRING COMMENT 'Linked product line',
  CUSTOMER_ID STRING COMMENT 'Customer impacted',
  PROJECT_TYPE STRING COMMENT 'NPI | Capacity | Upgrade | IT',
  OWNER_FUNCTION STRING COMMENT 'R&D | Ops | Field | IT',
  START_DATE DATE COMMENT 'Baseline start',
  END_DATE_PLANNED DATE COMMENT 'Planned finish',
  END_DATE_ACTUAL DATE COMMENT 'Actual finish (if complete)',
  CURRENT_STAGE_ID NUMBER(2) COMMENT 'Current gate',
  IS_ACTIVE BOOLEAN COMMENT 'Active flag',
  BUDGET_BASELINE_USD NUMBER(18,2) COMMENT 'Budget at creation',
  CONSTRAINT DIM_PROJECT_PK PRIMARY KEY (PROJECT_ID),
  CONSTRAINT FK_DIM_PROJECT_PROGRAM_ID FOREIGN KEY (PROGRAM_ID) REFERENCES EM_DB.PMO.DIM_PROGRAM (PROGRAM_ID),
  CONSTRAINT FK_DIM_PROJECT_PRODUCT_LINE_ID FOREIGN KEY (PRODUCT_LINE_ID) REFERENCES EM_DB.REVENUE.DIM_PRODUCT_LINE (PRODUCT_LINE_ID),
  CONSTRAINT FK_DIM_PROJECT_CUSTOMER_ID FOREIGN KEY (CUSTOMER_ID) REFERENCES EM_DB.REVENUE.DIM_CUSTOMER (CUSTOMER_ID),
  CONSTRAINT FK_DIM_PROJECT_CURRENT_STAGE_ID FOREIGN KEY (CURRENT_STAGE_ID) REFERENCES EM_DB.PMO.DIM_STAGE_GATE (STAGE_ID)
);

CREATE OR REPLACE TABLE EM_DB.PMO.FACT_PROGRESS (
  PROJECT_ID STRING COMMENT 'Project',
  SNAPSHOT_DATE DATE COMMENT 'Weekly snapshot date',
  COMPLETE_PCT NUMBER(5,2) COMMENT '% complete',
  EV_USD NUMBER(18,2) COMMENT 'Earned Value',
  PV_USD NUMBER(18,2) COMMENT 'Planned Value',
  AC_USD NUMBER(18,2) COMMENT 'Actual Cost',
  CPI NUMBER(8,3) COMMENT 'Cost Performance Index',
  SPI NUMBER(8,3) COMMENT 'Schedule Performance Index',
  STATUS STRING COMMENT 'ON_TRACK | DELAYED',
  CONSTRAINT FK_FACT_PROGRESS_PROJECT_ID FOREIGN KEY (PROJECT_ID) REFERENCES EM_DB.PMO.DIM_PROJECT (PROJECT_ID)
);

CREATE OR REPLACE TABLE EM_DB.PMO.FACT_FINANCIAL (
  PROJECT_ID STRING COMMENT 'Project',
  MONTH DATE COMMENT 'Month (period start)',
  BUDGET_MONTHLY_USD NUMBER(18,2) COMMENT 'Monthly budget',
  ACTUAL_SPEND_USD NUMBER(18,2) COMMENT 'Actual spend',
  CONSTRAINT FK_FACT_FINANCIAL_PROJECT_ID FOREIGN KEY (PROJECT_ID) REFERENCES EM_DB.PMO.DIM_PROJECT (PROJECT_ID)
);

CREATE OR REPLACE TABLE EM_DB.PMO.FACT_STAGE_STATUS (
  PROJECT_ID STRING COMMENT 'Project',
  STAGE_ID NUMBER(2) COMMENT 'Stage',
  GATE_DATE_PLANNED DATE COMMENT 'Planned date',
  GATE_DATE_ACTUAL DATE COMMENT 'Actual date',
  COMPLETE_PCT NUMBER(5,2) COMMENT 'Gate completion %',
  CONSTRAINT FK_FACT_STAGE_STATUS_PROJECT_ID FOREIGN KEY (PROJECT_ID) REFERENCES EM_DB.PMO.DIM_PROJECT (PROJECT_ID),
  CONSTRAINT FK_FACT_STAGE_STATUS_STAGE_ID FOREIGN KEY (STAGE_ID) REFERENCES EM_DB.PMO.DIM_STAGE_GATE (STAGE_ID)
);

CREATE OR REPLACE TABLE EM_DB.PMO.FACT_RESOURCE (
  PROJECT_ID STRING COMMENT 'Project',
  TEAM_ID STRING COMMENT 'Team',
  MONTH DATE COMMENT 'Month',
  HOURS_ALLOCATED NUMBER(10,2) COMMENT 'Allocated hours',
  HOURS_USED NUMBER(10,2) COMMENT 'Actual hours used',
  CONSTRAINT FK_FACT_RESOURCE_PROJECT_ID FOREIGN KEY (PROJECT_ID) REFERENCES EM_DB.PMO.DIM_PROJECT (PROJECT_ID),
  CONSTRAINT FK_FACT_RESOURCE_TEAM_ID FOREIGN KEY (TEAM_ID) REFERENCES EM_DB.PMO.DIM_TEAM (TEAM_ID)
);

CREATE OR REPLACE TABLE EM_DB.CUSTOMER.DIM_CUSTOMER_FEEDBACK_SOURCE (
  SOURCE_ID STRING COMMENT 'Feedback source key',
  SOURCE_NAME STRING COMMENT 'Source name',
  CONSTRAINT DIM_CUSTOMER_FEEDBACK_SOURCE_PK PRIMARY KEY (SOURCE_ID)
);

CREATE OR REPLACE TABLE EM_DB.CUSTOMER.FACT_CUSTOMER_HAPPINESS (
  PROJECT_ID STRING COMMENT 'Project',
  CUSTOMER_ID STRING COMMENT 'Customer',
  SOURCE_ID STRING COMMENT 'Feedback source',
  SURVEY_DATE DATE COMMENT 'Survey / VOC date',
  CSAT_SCORE NUMBER(3,1) COMMENT '1–5 satisfaction',
  NPS_SCORE NUMBER(3,0) COMMENT '-100 to +100',
  COMMENT_TEXT STRING COMMENT 'Free-text feedback',
  RESPONSE_TYPE STRING COMMENT 'Delivery | Performance | Support',
  ON_TIME_DELIVERY_PCT NUMBER(5,2) COMMENT 'Proxy from stage slip',
  ACCEPTANCE_DELAY_DAYS NUMBER(6,2) COMMENT 'Proxy lag to acceptance',
  MTBF_HOURS NUMBER(10,2) COMMENT 'Mean time between failure',
  MTTR_HOURS NUMBER(10,2) COMMENT 'Mean time to repair',
  SLA_ADHERENCE_PCT NUMBER(5,2) COMMENT 'Service SLA adherence',
  CONSTRAINT FK_FACT_CUSTOMER_HAPPINESS_PROJECT_ID FOREIGN KEY (PROJECT_ID) REFERENCES EM_DB.PMO.DIM_PROJECT (PROJECT_ID),
  CONSTRAINT FK_FACT_CUSTOMER_HAPPINESS_CUSTOMER_ID FOREIGN KEY (CUSTOMER_ID) REFERENCES EM_DB.REVENUE.DIM_CUSTOMER (CUSTOMER_ID),
  CONSTRAINT FK_FACT_CUSTOMER_HAPPINESS_SOURCE_ID FOREIGN KEY (SOURCE_ID) REFERENCES EM_DB.CUSTOMER.DIM_CUSTOMER_FEEDBACK_SOURCE (SOURCE_ID)
);

CREATE OR REPLACE TABLE EM_DB.RISK.DIM_RISK_CATEGORY (
  RISK_CATEGORY_ID STRING COMMENT 'Risk category key',
  RISK_CATEGORY_NAME STRING COMMENT 'Category name',
  CONSTRAINT DIM_RISK_CATEGORY_PK PRIMARY KEY (RISK_CATEGORY_ID)
);

CREATE OR REPLACE TABLE EM_DB.RISK.FACT_RISK_ENHANCED (
  PROJECT_ID STRING COMMENT 'Project',
  RISK_ID STRING COMMENT 'Risk identifier',
  RISK_TITLE STRING COMMENT 'Short risk title',
  RISK_CATEGORY_ID STRING COMMENT 'Risk category',
  RISK_CATEGORY_NAME STRING COMMENT 'Denormalized category name',
  IMPACT_TYPE STRING COMMENT 'Cost | Schedule | Technical | Quality | Regulatory',
  SEVERITY STRING COMMENT 'LOW | MEDIUM | HIGH | CRITICAL',
  PROBABILITY_PCT NUMBER(3,0) COMMENT 'Likelihood %',
  DETECTABILITY_SCORE NUMBER(1,0) COMMENT '1 easy – 5 hard',
  RPN NUMBER(6,0) COMMENT 'Risk Priority Number',
  EXPOSURE_SCORE NUMBER(6,2) COMMENT '0–100 normalized exposure',
  STATUS STRING COMMENT 'OPEN | MITIGATED | CLOSED | ESCALATED',
  OWNER STRING COMMENT 'Owning function/role',
  OPEN_DATE DATE COMMENT 'Open date',
  TARGET_CLOSE_DATE DATE COMMENT 'Target close',
  CLOSE_DATE DATE COMMENT 'Actual close (if any)',
  MITIGATION_ACTION STRING COMMENT 'Planned action',
  MITIGATION_STATUS STRING COMMENT 'Planned | In Progress | Complete',
  RESIDUAL_PROBABILITY_PCT NUMBER(3,0) COMMENT 'Residual likelihood %',
  SCHEDULE_IMPACT_DAYS NUMBER(6,0) COMMENT 'Expected schedule impact',
  FINANCIAL_IMPACT_USD NUMBER(18,2) COMMENT 'Worst-case cost impact',
  EXPECTED_FINANCIAL_IMPACT_USD NUMBER(18,2) COMMENT 'Probability-weighted cost',
  REVENUE_AT_RISK_USD NUMBER(18,2) COMMENT 'Proxy revenue at risk',
  ESCALATION_LEVEL STRING COMMENT 'Team | Program | Exec',
  CONSTRAINT FACT_RISK_ENHANCED_PK PRIMARY KEY (RISK_ID),
  CONSTRAINT FK_FACT_RISK_ENHANCED_PROJECT_ID FOREIGN KEY (PROJECT_ID) REFERENCES EM_DB.PMO.DIM_PROJECT (PROJECT_ID),
  CONSTRAINT FK_FACT_RISK_ENHANCED_RISK_CATEGORY_ID FOREIGN KEY (RISK_CATEGORY_ID) REFERENCES EM_DB.RISK.DIM_RISK_CATEGORY (RISK_CATEGORY_ID)
);

CREATE OR REPLACE TABLE EM_DB.HC.DIM_EMPLOYEE (
  EMPLOYEE_ID STRING COMMENT 'Employee ID',
  EMPLOYEE_NAME STRING COMMENT 'Employee name',
  ROLE STRING COMMENT 'Job role/title',
  FUNCTION STRING COMMENT 'Eng | Field | IT | Mfg',
  LOCATION STRING COMMENT 'Work location',
  SKILL_SET STRING COMMENT 'Comma-separated key skills',
  GRADE STRING COMMENT 'Level (IC2..Mgr2)',
  MANAGER_ID STRING COMMENT 'Manager (self-ref)',
  HIRE_DATE DATE COMMENT 'Hire date',
  STATUS STRING COMMENT 'Active | Leave | Separated',
  CONSTRAINT DIM_EMPLOYEE_PK PRIMARY KEY (EMPLOYEE_ID),
  CONSTRAINT FK_DIM_EMPLOYEE_MANAGER_ID FOREIGN KEY (MANAGER_ID) REFERENCES EM_DB.HC.DIM_EMPLOYEE (EMPLOYEE_ID)
);

CREATE OR REPLACE TABLE EM_DB.HC.FACT_RESOURCE_CAPACITY (
  EMPLOYEE_ID STRING COMMENT 'Employee',
  MONTH DATE COMMENT 'Month (period start)',
  HOURS_AVAILABLE NUMBER(10,2) COMMENT 'Available capacity hours',
  HOURS_ALLOCATED NUMBER(10,2) COMMENT 'Allocated hours',
  PROJECT_ID STRING COMMENT 'Assigned project (nullable)',
  TEAM_ID STRING COMMENT 'Team alignment',
  CONSTRAINT FK_FACT_RESOURCE_CAPACITY_EMPLOYEE_ID FOREIGN KEY (EMPLOYEE_ID) REFERENCES EM_DB.HC.DIM_EMPLOYEE (EMPLOYEE_ID),
  CONSTRAINT FK_FACT_RESOURCE_CAPACITY_PROJECT_ID FOREIGN KEY (PROJECT_ID) REFERENCES EM_DB.PMO.DIM_PROJECT (PROJECT_ID),
  CONSTRAINT FK_FACT_RESOURCE_CAPACITY_TEAM_ID FOREIGN KEY (TEAM_ID) REFERENCES EM_DB.PMO.DIM_TEAM (TEAM_ID)
);

CREATE OR REPLACE TABLE EM_DB.HC.FACT_EMPLOYEE_PERFORMANCE (
  EMPLOYEE_ID STRING COMMENT 'Employee',
  REVIEW_PERIOD DATE COMMENT 'Quarter start',
  PROJECTS_SUPPORTED NUMBER(3,0) COMMENT '# projects this period',
  AVG_CPI NUMBER(5,2) COMMENT 'Avg CPI contribution (proxy)',
  QUALITY_SCORE NUMBER(5,2) COMMENT 'Quality rating 1–5',
  TRAINING_HOURS NUMBER(5,2) COMMENT 'Training hours in period',
  ENGAGEMENT_SCORE NUMBER(5,2) COMMENT 'Engagement 1–5',
  ATTRITION_RISK STRING COMMENT 'Low | Medium | High',
  CONSTRAINT FK_FACT_EMPLOYEE_PERFORMANCE_EMPLOYEE_ID FOREIGN KEY (EMPLOYEE_ID) REFERENCES EM_DB.HC.DIM_EMPLOYEE (EMPLOYEE_ID)
);

CREATE OR REPLACE TABLE EM_DB.GOV.DIM_GOV_POLICY (
  POLICY_ID STRING COMMENT 'Policy ID',
  POLICY_NAME STRING COMMENT 'Policy title',
  CATEGORY STRING COMMENT 'Procurement | Logistics | ESG | Quality',
  OWNER_ROLE STRING COMMENT 'Policy owner role',
  EFFECTIVE_DATE DATE COMMENT 'Effective date',
  REVIEW_FREQUENCY STRING COMMENT 'e.g., Quarterly',
  CONSTRAINT DIM_GOV_POLICY_PK PRIMARY KEY (POLICY_ID)
);

CREATE OR REPLACE TABLE EM_DB.GOV.FACT_GOVERNANCE_COMPLIANCE (
  POLICY_ID STRING COMMENT 'Policy applied',
  SUPPLIER_ID STRING COMMENT 'Supplier (if tracked)',
  PROJECT_ID STRING COMMENT 'Project (if applicable)',
  EVAL_DATE DATE COMMENT 'Evaluation date',
  IS_COMPLIANT BOOLEAN COMMENT 'Compliance flag',
  NON_COMPLIANCE_REASON STRING COMMENT 'Why not compliant',
  AUDITOR STRING COMMENT 'Reviewer / auditor',
  CORRECTIVE_ACTION STRING COMMENT 'CAPA / action to resolve',
  ACTION_DUE_DATE DATE COMMENT 'Action due date',
  ACTION_STATUS STRING COMMENT 'Planned | In Progress | Closed',
  LAST_UPDATED TIMESTAMP_NTZ COMMENT 'System timestamp',
  CONSTRAINT FK_FACT_GOVERNANCE_COMPLIANCE_POLICY_ID FOREIGN KEY (POLICY_ID) REFERENCES EM_DB.GOV.DIM_GOV_POLICY (POLICY_ID),
  CONSTRAINT FK_FACT_GOVERNANCE_COMPLIANCE_PROJECT_ID FOREIGN KEY (PROJECT_ID) REFERENCES EM_DB.PMO.DIM_PROJECT (PROJECT_ID)
);

CREATE OR REPLACE SCHEMA EM_DB.METRICS;

CREATE OR REPLACE TABLE EM_DB.METRICS.FACT_PORTFOLIO_METRIC (
    METRIC_ID            STRING,
    METRIC_NAME          STRING,      -- Revenue, Profitability, etc.
    METRIC_CATEGORY      STRING,      -- FINANCIAL | DELIVERY | CUSTOMER | PEOPLE | RISK | GOVERNANCE
    PERIOD_TYPE          STRING,      -- MONTH | QUARTER | YEAR
    PERIOD_LABEL         STRING,      -- 2025-01, 2025-Q1, 2025
    PERIOD_START_DATE    DATE,
    PERIOD_END_DATE      DATE,
    VALUE_NUM            FLOAT,       -- The “65”, “78”, “32”, etc.
    VALUE_UNIT           STRING,      -- %
    TARGET_NUM           FLOAT,       -- Optional
    TARGET_UNIT          STRING,
    PCT_OF_TARGET        FLOAT,
    HEALTH_STATUS        STRING,      -- GOOD | WARN | BAD
    UPDATED_AT           TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE EM_DB.METRICS.FACT_TIMELINE_HEALTH (
    PERIOD_TYPE          STRING,
    PERIOD_LABEL         STRING,
    PERIOD_START_DATE    DATE,
    PERIOD_END_DATE      DATE,
    RED_COUNT            INTEGER,
    YELLOW_COUNT         INTEGER,
    GREEN_COUNT          INTEGER,
    TOTAL_COUNT          INTEGER,
    HEALTH_SCORE         FLOAT,
    UPDATED_AT           TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE SCHEMA EM_DB.OKR;


CREATE OR REPLACE TABLE EM_DB.OKR.DIM_OKR (
    OKR_ID               STRING,
    OBJECTIVE_TITLE      STRING,
    KEY_RESULT_TITLE     STRING,
    OWNER                STRING,
    STATUS               STRING,       -- ON_TRACK | AT_RISK | BEHIND
    PERIOD_TYPE          STRING,
    PERIOD_LABEL         STRING,
    PERIOD_START_DATE    DATE,
    PERIOD_END_DATE      DATE,
    UPDATED_AT           TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

