USE ROLE SYSADMIN;
  
SHOW WAREHOUSES;

CREATE OR REPLACE USER USER_DATAENG
  PASSWORD='StrongPassword123!'
  DEFAULT_ROLE=DATA_ENGINEER
  DEFAULT_WAREHOUSE=ENTERPRISE_WH;

CREATE OR REPLACE USER USER_ANALYST
  PASSWORD='StrongPassword123!'
  DEFAULT_ROLE=ANALYST
  DEFAULT_WAREHOUSE=ENTERPRISE_WH;

CREATE OR REPLACE USER USER_APP
  PASSWORD='StrongPassword123!'
  DEFAULT_ROLE=APP_USER
  DEFAULT_WAREHOUSE=ENTERPRISE_WH;

Airbyte hs7cR7v8nVSk0mfKlvqy8OqAKUA15Mat

