/**********************************************************************
-- Enterprise Metrics Data Warehouse Setup - Snowflake
-- Deployment-ready SQL Script
-- Author: Auto-generated
-- Description: Creates warehouse, database, schemas, roles, users,
--              grants, and all core dimensions/fact tables for
--              enterprise metrics platform.
**********************************************************************/

/* ================================
   1?? CREATE WAREHOUSE
================================ */
CREATE OR REPLACE WAREHOUSE EA_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Warehouse for Enterprise Accountability workloads';

/* ================================
   2?? CREATE DATABASE
================================ */
CREATE OR REPLACE DATABASE EA_DB
  COMMENT = 'Enterprise Accountability Data Warehouse';

/* ================================
   3?? CREATE SCHEMAS
================================ */
CREATE OR REPLACE SCHEMA EA_DB.DIMENSIONS;
CREATE OR REPLACE SCHEMA EA_DB.FACTS;
CREATE OR REPLACE SCHEMA EA_DB.GOVERNANCE;
CREATE OR REPLACE SCHEMA EA_DB.UTILS;

/* ================================
   4?? CREATE ROLES
================================ */
CREATE OR REPLACE ROLE ORG_ADMIN;
CREATE OR REPLACE ROLE DATA_ENGINEER;
CREATE OR REPLACE ROLE DATA_SCIENTIST;
CREATE OR REPLACE ROLE ANALYST;
CREATE OR REPLACE ROLE APP_USER;
CREATE OR REPLACE ROLE SECURITY_ADMIN;

/* Role hierarchy */
GRANT ROLE DATA_ENGINEER TO ROLE ORG_ADMIN;
GRANT ROLE DATA_SCIENTIST TO ROLE DATA_ENGINEER;
GRANT ROLE ANALYST TO ROLE DATA_SCIENTIST;
GRANT ROLE APP_USER TO ROLE ANALYST;
GRANT ROLE SECURITY_ADMIN TO ROLE ORG_ADMIN;

/* ================================
   5?? CREATE USERS
================================ */
CREATE OR REPLACE USER USER_DATAENG
  PASSWORD='StrongPassword123!'
  DEFAULT_ROLE=DATA_ENGINEER
  DEFAULT_WAREHOUSE=EA_WH;

CREATE OR REPLACE USER USER_ANALYST
  PASSWORD='StrongPassword123!'
  DEFAULT_ROLE=ANALYST
  DEFAULT_WAREHOUSE=EA_WH;

CREATE OR REPLACE USER USER_APP
  PASSWORD='StrongPassword123!'
  DEFAULT_ROLE=APP_USER
  DEFAULT_WAREHOUSE=EA_WH;

/* Assign roles to users */
GRANT ROLE DATA_ENGINEER TO USER USER_DATAENG;
GRANT ROLE ANALYST TO USER USER_ANALYST;
GRANT ROLE APP_USER TO USER USER_APP;

/* ================================
   6?? GRANT PRIVILEGES
================================ */
/* Warehouse access */
GRANT USAGE ON WAREHOUSE EA_WH TO ROLE DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE EA_WH TO ROLE DATA_SCIENTIST;
GRANT USAGE ON WAREHOUSE EA_WH TO ROLE ANALYST;
GRANT USAGE ON WAREHOUSE EA_WH TO ROLE APP_USER;

/* Database access */
GRANT USAGE ON DATABASE EA_DB TO ROLE DATA_ENGINEER;
GRANT USAGE ON DATABASE EA_DB TO ROLE DATA_SCIENTIST;
GRANT USAGE ON DATABASE EA_DB TO ROLE ANALYST;
GRANT USAGE ON DATABASE EA_DB TO ROLE APP_USER;

/* Schema usage */
GRANT USAGE ON ALL SCHEMAS IN DATABASE EA_DB TO ROLE DATA_ENGINEER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE EA_DB TO ROLE DATA_SCIENTIST;
GRANT USAGE ON ALL SCHEMAS IN DATABASE EA_DB TO ROLE ANALYST;
GRANT USAGE ON ALL SCHEMAS IN DATABASE EA_DB TO ROLE APP_USER;

/* DDL/DML privileges */
GRANT CREATE TABLE, INSERT, UPDATE, DELETE, SELECT ON ALL SCHEMA IN DATABASE EA_DB TO ROLE DATA_ENGINEER;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA EA_DB.FACTS TO ROLE DATA_SCIENTIST;
GRANT SELECT ON ALL TABLES IN DATABASE EA_DB TO ROLE ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA EA_DB.FACTS TO ROLE APP_USER;

/* ================================
   7?? CREATE DIMENSIONS TABLES
================================ */
USE SCHEMA EA_DB.DIMENSIONS;

CREATE OR REPLACE TABLE DIM_DATE (
    DATE_KEY DATE PRIMARY KEY,
    YEAR INT,
    QUARTER INT,
    MONTH INT,
    MONTH_NAME STRING,
    WEEK INT,
    DAY_OF_WEEK STRING,
    IS_WEEKEND BOOLEAN
);

CREATE OR REPLACE TABLE DIM_ORG_UNIT (
    ORG_UNIT_ID STRING PRIMARY KEY,
    ORG_UNIT_NAME STRING,
    ORG_LEVEL STRING,
    PARENT_ORG_UNIT_ID STRING,
    HEAD_OF_UNIT STRING,
    REGION STRING,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE DIM_ENTITY (
    ENTITY_ID STRING PRIMARY KEY,
    ENTITY_TYPE STRING,
    ENTITY_NAME STRING,
    STATUS STRING,
    OWNER STRING,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE DIM_METRICS (
    METRIC_ID STRING PRIMARY KEY,
    METRIC_NAME STRING,
    METRIC_DESCRIPTION STRING,
    METRIC_CATEGORY STRING,
    UNIT_OF_MEASURE STRING,
    AGGREGATION_TYPE STRING,
    DATA_SOURCE STRING,
    OWNER_DEPARTMENT STRING,
    REFRESH_FREQUENCY STRING,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

/* ================================
   8?? CREATE FACT TABLES
================================ */
USE SCHEMA EA_DB.FACTS;

CREATE OR REPLACE TABLE FACT_METRICS (
    METRIC_ID STRING REFERENCES EA_DB.DIMENSIONS.DIM_METRICS(METRIC_ID),
    DATE_KEY DATE REFERENCES EA_DB.DIMENSIONS.DIM_DATE(DATE_KEY),
    ORG_UNIT_ID STRING REFERENCES EA_DB.DIMENSIONS.DIM_ORG_UNIT(ORG_UNIT_ID),
    ENTITY_ID STRING REFERENCES EA_DB.DIMENSIONS.DIM_ENTITY(ENTITY_ID),
    VALUE FLOAT,
    TARGET_VALUE FLOAT,
    VARIANCE FLOAT,
    CURRENCY_CODE STRING,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (METRIC_ID, DATE_KEY, ORG_UNIT_ID, ENTITY_ID)
)
CLUSTER BY (METRIC_ID, DATE_KEY);

CREATE OR REPLACE TABLE FACT_FORECASTS (
    METRIC_ID STRING REFERENCES EA_DB.DIMENSIONS.DIM_METRICS(METRIC_ID),
    DATE_KEY DATE REFERENCES EA_DB.DIMENSIONS.DIM_DATE(DATE_KEY),
    ORG_UNIT_ID STRING REFERENCES EA_DB.DIMENSIONS.DIM_ORG_UNIT(ORG_UNIT_ID),
    ENTITY_ID STRING REFERENCES EA_DB.DIMENSIONS.DIM_ENTITY(ENTITY_ID),
    FORECAST_VALUE FLOAT,
    CONFIDENCE_LEVEL FLOAT,
    MODEL_NAME STRING,
    GENERATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (METRIC_ID, DATE_KEY, ORG_UNIT_ID, ENTITY_ID)
)
CLUSTER BY (METRIC_ID, DATE_KEY);

/* ================================
   9?? CREATE GOVERNANCE TABLE
================================ */
USE SCHEMA EA_DB.GOVERNANCE;

CREATE OR REPLACE TABLE METRIC_GOVERNANCE (
    METRIC_ID STRING REFERENCES EA_DB.DIMENSIONS.DIM_METRICS(METRIC_ID),
    VERSION_NUMBER INT,
    APPROVAL_STATUS STRING,
    CHANGE_REASON STRING,
    APPROVED_BY STRING,
    APPROVED_AT TIMESTAMP_NTZ,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (METRIC_ID, VERSION_NUMBER)
);

CREATE OR REPLACE TABLE DIMENSIONS.METRIC_GRAPH_EDGE (
  CHILD_METRIC_ID     STRING NOT NULL
    REFERENCES EA_DB.DIMENSIONS.DIM_METRICS(METRIC_ID),
  PARENT_METRIC_ID    STRING NOT NULL
    REFERENCES EA_DB.DIMENSIONS.DIM_METRICS(METRIC_ID),
  RELATIONSHIP_TYPE STRING DEFAULT 'BELONGS_TO',     -- e.g., CATEGORY_OF, COMPONENT_OF, ALTERNATE_OF
  EFF_START         DATE   NOT NULL,
  EFF_END DATE NOT NULL DEFAULT (DATE '9999-12-31'),
  EDGE_WEIGHT       NUMBER(18,6),                    -- optional (e.g., % allocation, priority)
  CREATED_AT        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT        TIMESTAMP_NTZ,

  CONSTRAINT METRIC_GRAPH_EDGE_PK PRIMARY KEY (CHILD_METRIC_ID, PARENT_METRIC_ID, EFF_START)

  -- Disallow zero-length intervals
  -- CONSTRAINT ITEM_GRAPH_EDGE_CHK_DATES CHECK(EFF_END > EFF_START)
);

CREATE OR REPLACE TABLE DIMENSIONS.METRIC_ASSOCIATED_LIST (
  MAIN_METRIC_ID     STRING NOT NULL
    REFERENCES EA_DB.DIMENSIONS.DIM_METRICS(METRIC_ID),
  ASSOC_METRIC_ID    STRING NOT NULL
    REFERENCES EA_DB.DIMENSIONS.DIM_METRICS(METRIC_ID),
  RELATIONSHIP_TYPE STRING DEFAULT 'BELONGS_TO',     -- e.g., CATEGORY_OF, COMPONENT_OF, ALTERNATE_OF
  EFF_START         DATE   NOT NULL,
  EFF_END DATE NOT NULL DEFAULT (DATE '9999-12-31'),
  ASSOC_WEIGHT       NUMBER(18,6),                    -- optional (e.g., % allocation, priority)
  CREATED_AT        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT        TIMESTAMP_NTZ,

  CONSTRAINT METRIC_ASSOC_LIST_PK PRIMARY KEY (MAIN_METRIC_ID, ASSOC_METRIC_ID, EFF_START)

  -- Disallow zero-length intervals
  -- CONSTRAINT ITEM_GRAPH_EDGE_CHK_DATES CHECK(EFF_END > EFF_START)
);

-- Ensure you don’t “double-book” the same parent-child across overlapping intervals.
-- Snowflake can’t do temporal exclusion constraints natively, so enforce in ETL/dbt tests
-- or add a task/proc that rejects overlapping rows for the same CHILD,PARENT pair.


/* ================================
   ?? CREATE UTILS TABLE
================================ */
USE SCHEMA EA_DB.UTILS;

CREATE OR REPLACE TABLE DIM_SOURCE_SYSTEM (
    SOURCE_SYSTEM_ID STRING PRIMARY KEY,
    SOURCE_NAME STRING,
    SYSTEM_TYPE STRING,
    OWNER STRING,
    CONTACT_EMAIL STRING,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

/* ================================
   ? DEPLOYMENT COMPLETE
================================ */
